# Netlify configuration for Colorado Trip Planner

[build]
  # No build process needed for static site
  publish = "."

[build.environment]
  # Environment variables (if needed)

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # Redirect from any path to start.html for landing page
  from = "/start"
  to = "/start.html"
  status = 200

[[redirects]]
  # Redirect from any path to demo.html
  from = "/demo"
  to = "/demo.html"
  status = 200

[[redirects]]
  # Redirect from root to start page
  from = "/"
  to = "/start.html"
  status = 200

# Enable form processing (if you add contact forms later)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true